# Generated by Django 3.1.7 on 2021-03-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='libraries',
            field=models.ManyToManyField(related_name='book_library', to='book.Library'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='library',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leads_library', to='book.library'),
        ),
    ]
