# Generated by Django 3.1.7 on 2021-03-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210309_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_library', to='book.library'),
        ),
    ]
